-- ============================================================================
-- Blog: AI-generated SEO posts published on a weekly cron.
--
-- Each post is generated by Claude in the Wonderland Playhouse voice,
-- targeting a primary keyword we want to rank for (e.g. "kids birthday party
-- Brooklyn", "birthday play space NYC"). The cron job picks 3 fresh topics
-- per Monday, avoiding duplicates of recently published posts.
--
-- Content is stored as structured JSON blocks (no raw HTML) so rendering is
-- safe and consistent.
-- ============================================================================

create table blog_posts (
  id uuid primary key default uuid_generate_v4(),

  -- URL slug: /blog/[slug]. Unique, kebab-case.
  slug text unique not null,

  title text not null,
  excerpt text not null,                -- meta description / list view subtitle (~155 chars)

  -- Structured content: array of typed blocks (h2, h3, p, ul, ol, quote, cta).
  -- Rendered by app/blog/[slug]/page.tsx as JSX — no HTML escaping needed.
  content jsonb not null,

  -- SEO
  primary_keyword text,                 -- the main keyword the post targets
  keywords text[] default '{}',         -- secondary keywords for og:keywords meta
  hero_emoji text default '✨',

  -- Lifecycle
  status text not null default 'published' check (
    status in ('draft', 'published', 'archived')
  ),
  published_at timestamptz,

  -- Provenance
  generated_by text default 'ai',       -- 'ai' or 'manual'
  model text,                           -- e.g. 'claude-sonnet-4-6'

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index blog_posts_slug_idx on blog_posts(slug);
create index blog_posts_status_published_at_idx on blog_posts(status, published_at desc);
create index blog_posts_primary_keyword_idx on blog_posts(primary_keyword);

create trigger blog_posts_updated_at before update on blog_posts
  for each row execute function set_updated_at();

alter table blog_posts enable row level security;

-- Public can SELECT only published posts (used by the public /blog routes
-- via the anon key). Service role does everything (admin + generator).
create policy blog_posts_public_read on blog_posts for select
  using (status = 'published');
create policy blog_posts_service_role on blog_posts for all
  using (auth.role() = 'service_role');
